sudo : required
services : 
  - docker
before_install:
  - docker build -t neha/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run neha/complex npm test -- --coverage

after_success:
  - docker build -t neha/multi-client ./client
  - docker build -t neha/multi-nginx ./nginx
  - docker build -t neha/multi-server ./server
  - docker build -t neha/multi-worker ./worker

