sudo : required
services : 
  - docker
before_install:
  - docker build -t neha/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run neha/complex npm test -- --coverage

after_success:
  - docker build -t neha/multi-client ./client
  - docker build -t neha/multi-nginx ./nginx
  - docker build -t neha/multi-server ./server
  - docker build -t neha/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push neha/multi-client
  - docker push neha/multi-nginx
  - docker push neha/multi-server
  - docker push neha/multi-worker
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi_docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-954516000444
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id : 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure : "$AWS_SECRET_KEY"




